SRC_PROCESS=Shape.c Square.c Rectangle.c RoundedSquare.c RoundedRectangle.c AbstractFactory.c RoundedShapeFactory.c ShapeFactory.c main.c
EXE_PROCESS=main
CFLAGS=-Wall


all:
	gcc ${CFLAGS} ${SRC_PROCESS} -o ${EXE_PROCESS}

clean:
	rm -f ${EXE_PROCESS}